# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
    ]
