# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.IntegerField(default=0),
        ),
    ]
